# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638ffbbcfc55ea59b0d7f09c7ddc52af6a16b40877f061feec71df7086f44dc11bb2372035e41af9ab7dff846a722850d217b8d0139d994fa545834c65623f44

test:
  secret_key_base: a8e2a746c8746339cc6b6ecebeb06d6f9431e6596f971809af39c61e487e376ba702be54edd803f448c457ce98ae63074457bb915d971b99b017853c18ccbd95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
